### ISSUE TITLE
Detail Page

### ISSUE THREAD

**Issue by MunYeong0723** [IMHOJEONG/Customize_KT_Enterprise#2]
AI 호텔 서비스 상세페이지 구현

<br>

[TODO]

- [x] 이런 고민을 한 적 있는 호텔 오너라면?
- [x] ‘세계 최초 국내 유일’ KT AI 호텔을 만나보세요.
- [x] AI 호텔은 이렇게 구성되어 있어요.
- [x] 어떻게 설치가 되나요?
- [x] 체크인부터 체크아웃까지, AI 호텔이 함께 합니다.
- [x] 요금 안내
- [x] AI 호텔을 더 알고 싶다면? ([관련 PR](https://github.com/IMHOJEONG/Rookie-Camp_third/pull/1))
- [x] 이미 많은 AI 호텔이 성공적으로 운영중입니다.
- [x] header, footer 연결

**Comment by IMHOJEONG** [comment]
전부 구현 완료하였습니다.
