### ISSUE TITLE
Main Page

### ISSUE THREAD

**Issue by MunYeong0723** [IMHOJEONG/Customize_KT_Enterprise#4]
KT Enterprise의 메인페이지 구현
<br>

- [x] 전체 레이아웃 구성
- [x] 메뉴 첫번째 탭 구현
- [x] 메뉴 두번째 탭 구현
- [x] 메뉴 세번째 탭 구현

**Comment by IMHOJEONG** [comment]
메인 페이지 메뉴 전부 구현 완료
