### ISSUE TITLE
Menu Component

### ISSUE THREAD

**Issue by MunYeong0723** [IMHOJEONG/Customize_KT_Enterprise#5]
메인페이지와 header에 연결되는 menu component 구현
- 마우스 올렸을 때 하위 카테고리가 보이도록 구현
- 메인페이지에서의 메뉴와 상세페이지에서의 메뉴 디자인을 **다르게 구현**하기로 결정

**Comment by IMHOJEONG** [comment]
메인 메뉴와 detail page의 메뉴를 다르게 구성 완료
